//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopApp.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NotAThiefDataBaseEntities : DbContext
    {
        public NotAThiefDataBaseEntities()
            : base("name=NotAThiefDataBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Exercise> Exercise { get; set; }
        public virtual DbSet<ExerciseOfStudent> ExerciseOfStudent { get; set; }
        public virtual DbSet<FileInTask> FileInTask { get; set; }
        public virtual DbSet<Group> Group { get; set; }
        public virtual DbSet<Question> Question { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<Subject> Subject { get; set; }
        public virtual DbSet<SubjectOfTeacher> SubjectOfTeacher { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Task> Task { get; set; }
        public virtual DbSet<TaskType> TaskType { get; set; }
        public virtual DbSet<TypeOfExercise> TypeOfExercise { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Variable> Variable { get; set; }
        public virtual DbSet<VariableValue> VariableValue { get; set; }
    }
}
