//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExerciseOfStudent
    {
        public int ExerciseId { get; set; }
        public int StudentId { get; set; }
        public int Id { get; set; }
        public string Mark { get; set; }
        public string Comment { get; set; }
        public int StatusId { get; set; }
        public int SubjectOfTeacherId { get; set; }
    
        public virtual Exercise Exercise { get; set; }
        public virtual Status Status { get; set; }
        public virtual Student Student { get; set; }
        public virtual SubjectOfTeacher SubjectOfTeacher { get; set; }
    }
}
